# Generated by Django 2.0 on 2017-12-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'db_table': 'todos',
            },
        ),
    ]
